
package Homework2025.BridgeSegment.BChau;

import BridgeSegment.*;
import simView.*;

import java.awt.*;

public class BridgeSystem extends AbstractBridgeSystem {

	public BridgeSystem() {
		this("BridgeSystem");
	}

	public BridgeSystem(String name) {
		super(name);

		BridgeSegment BridgeSegment1 = new BridgeSegment("BridgeSegment1", 1, BridgeSystemSetting.Bridge1InitialState,
				AbstractBridgeSystem.BridgeSystemSetting.Bridge1TrafficLightDurationTime);
		BridgeSegment BridgeSegment2 = new BridgeSegment("BridgeSegment2", 2, BridgeSystemSetting.Bridge2InitialState,
				AbstractBridgeSystem.BridgeSystemSetting.Bridge2TrafficLightDurationTime);
		BridgeSegment BridgeSegment3 = new BridgeSegment("BridgeSegment3", 3, BridgeSystemSetting.Bridge3InitialState,
				AbstractBridgeSystem.BridgeSystemSetting.Bridge3TrafficLightDurationTime);

		add(westCarGenerator);
		add(eastCarGenerator);
		add(BridgeSegment1);
		add(BridgeSegment2);
		add(BridgeSegment3);
		add(this.transduser);
		addCoupling(this.westCarGenerator, "out", BridgeSegment3, "westbound_in");
		addCoupling(this.eastCarGenerator, "out", BridgeSegment1, "eastbound_in");

		addCoupling(BridgeSegment3, "westbound_out", this, "westbound_in");

		addCoupling(BridgeSegment3, "eastbound_out", BridgeSegment2, "westbound_in");
		addCoupling(BridgeSegment2, "eastbound_out", BridgeSegment1, "westbound_in");

		addCoupling(BridgeSegment1, "westbound_out", BridgeSegment2, "eastbound_in");
		addCoupling(BridgeSegment2, "westbound_out", BridgeSegment3, "eastbound_in");

		addCoupling(BridgeSegment1, "eastbound_out", this, "eastbound_out");

		addCoupling(BridgeSegment1, "eastbound_out", this.transduser,
				"Bridge1_EastOut");
		addCoupling(BridgeSegment1, "westbound_out", this.transduser,
				"Bridge1_WestOut");
		addCoupling(BridgeSegment2, "eastbound_out", this.transduser,
				"Bridge2_EastOut");
		addCoupling(BridgeSegment2, "westbound_out", this.transduser,
				"Bridge2_WestOut");
		addCoupling(BridgeSegment3, "eastbound_out", this.transduser,
				"Bridge3_EastOut");
		addCoupling(BridgeSegment3, "westbound_out", this.transduser,
				"Bridge3_WestOut");
	}

	/**
	 * Automatically generated by the SimView program.
	 * Do not edit this manually, as such changes will get overwritten.
	 */
	public void layoutForSimView() {
		preferredSize = new Dimension(1618, 568);
		if ((ViewableComponent) withName("BridgeSegment3") != null)
			((ViewableComponent) withName("BridgeSegment3")).setPreferredLocation(new Point(216, 276));
		if ((ViewableComponent) withName("BridgeSegment1") != null)
			((ViewableComponent) withName("BridgeSegment1")).setPreferredLocation(new Point(916, 284));
		if ((ViewableComponent) withName("Transducer") != null)
			((ViewableComponent) withName("Transducer")).setPreferredLocation(new Point(442, 60));
		if ((ViewableComponent) withName("EastGen") != null)
			((ViewableComponent) withName("EastGen")).setPreferredLocation(new Point(1374, 280));
		if ((ViewableComponent) withName("WestGen") != null)
			((ViewableComponent) withName("WestGen")).setPreferredLocation(new Point(2, 273));
		if ((ViewableComponent) withName("BridgeSegment2") != null)
			((ViewableComponent) withName("BridgeSegment2")).setPreferredLocation(new Point(575, 281));
	}
}
